### ISSUE TITLE
Jump with caret before the character

### ISSUE THREAD

**Issue by wilkerlucio** [schoettker/AceJump-Reloaded#1]
Hello, first, thank you very much for making this work again on IntelliJ 2024.3!!

In the AceJump Light there was an option to configure the jump to go before the matched char. I notice in yours I can only jump with the caret after the matched char.

Can you please also add the option to jump to before the char?

Thanks!

**Comment by schoettker** [comment]
Hey! Sorry for the late response, somehow missed your message! 
I just published an update to make this work again, it can take up to 2 business days for Jetbrains to verify the update but then it should be possible for you to update and have this option working again 😊 
This will also be the default behaviour now as it feels more natural!
<img width="797" alt="image" src="https://github.com/user-attachments/assets/a83922d3-ce68-4566-aa98-4dbc2c4f4164" />

**Comment by arialdomartini** [comment]
Incredible work. Thank you.

**Comment by schoettker** [comment]
Closing this as the v1.0.1 update to support this has been released to the marketplace 😊

**Comment by arialdomartini** [comment]
You are amazing! Thank you!
